quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/photoshare}
quarkus.datasource.username=${DB_USERNAME:photoshare}
quarkus.datasource.password=${DB_PASSWORD:photoshare}
#quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true

quarkus.hibernate-orm.log.sql=true

quarkus.datasource.jdbc.max-size=16

quarkus.redis.hosts=redis://host.docker.internal:6379

redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT:6379}

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}
mp.messaging.outgoing.post-liked.connector=smallrye-kafka
mp.messaging.outgoing.post-liked.topic=post-liked
mp.messaging.outgoing.post-liked.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.incoming.post-liked-in.connector=smallrye-kafka
mp.messaging.incoming.post-liked-in.topic=post-liked
mp.messaging.incoming.post-liked-in.value.deserializer=com.ariv.photoshare.events.PostLikedEventDeserializer
mp.messaging.incoming.post-liked-in.auto.offset.reset=earliest

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics
quarkus.http.host=0.0.0.0

# MinIO
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket=photoshare

%dev.quarkus.datasource.dev-ui.allow-sql=true

quarkus.otel.enabled=true
quarkus.otel.exporter.otlp.endpoint=http://host.docker.internal:4318
quarkus.application.name=photo-sharing-api

app.environment=${APP_ENVIRONMENT:local}






