quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/photoshare

#quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true

quarkus.hibernate-orm.log.sql=true

quarkus.datasource.jdbc.max-size=16

quarkus.redis.hosts=redis://localhost:6379

kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.post-liked.connector=smallrye-kafka
mp.messaging.outgoing.post-liked.topic=post-liked
mp.messaging.outgoing.post-liked.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.incoming.post-liked-in.connector=smallrye-kafka
mp.messaging.incoming.post-liked-in.topic=post-liked
mp.messaging.incoming.post-liked-in.value.deserializer=com.ariv.photoshare.events.PostLikedEventDeserializer
mp.messaging.incoming.post-liked-in.auto.offset.reset=earliest

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics
quarkus.http.host=0.0.0.0

# MinIO

minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket=photoshare