quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/photoshare}
quarkus.datasource.username=${DB_USERNAME:admin}
quarkus.datasource.password=${DB_PASSWORD:admin}


quarkus.datasource."feed-replica".db-kind=postgresql
quarkus.datasource."feed-replica".jdbc.url=${FEED_REPLICA_DB_URL:jdbc:postgresql://localhost:5433/photoshare}
quarkus.datasource."feed-replica".username=${FEED_REPLICA_DB_USERNAME:feed_reader}
quarkus.datasource."feed-replica".password=${FEED_REPLICA_DB_PASSWORD:feed_reader_password}

quarkus.datasource."feed-replica".jdbc.min-size=2
quarkus.datasource."feed-replica".jdbc.max-size=12
quarkus.datasource."feed-replica".jdbc.acquisition-timeout=3s

#quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true

quarkus.hibernate-orm.log.sql=true

quarkus.datasource.jdbc.max-size=16

quarkus.redis.hosts=${REDIS_HOSTS:redis://localhost:6379}

redis.host=${REDIS_HOST:localhost}
redis.port=${REDIS_PORT:6379}

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
mp.messaging.outgoing.post-liked.connector=smallrye-kafka
mp.messaging.outgoing.post-liked.topic=post-liked
mp.messaging.outgoing.post-liked.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.incoming.post-liked-in.connector=smallrye-kafka
mp.messaging.incoming.post-liked-in.topic=post-liked
mp.messaging.incoming.post-liked-in.value.deserializer=com.ariv.photoshare.events.PostLikedEventDeserializer
mp.messaging.incoming.post-liked-in.auto.offset.reset=earliest

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics
quarkus.http.host=0.0.0.0

# MinIO
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:admin}
minio.secret-key=${MINIO_SECRET_KEY:password123}
minio.bucket=photoshare

%dev.quarkus.datasource.dev-ui.allow-sql=true

quarkus.otel.enabled=true
quarkus.otel.exporter.otlp.endpoint=http://host.docker.internal:4318
quarkus.application.name=photo-sharing-api

app.environment=${APP_ENVIRONMENT:local}

feed.celebrity-threshold=${FEED_CELEBRITY_THRESHOLD:1}

# Post-created producer
mp.messaging.outgoing.post-created.connector=smallrye-kafka
mp.messaging.outgoing.post-created.topic=post-created
mp.messaging.outgoing.post-created.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Post-created consumer
mp.messaging.incoming.post-created-in.connector=smallrye-kafka
mp.messaging.incoming.post-created-in.topic=post-created
mp.messaging.incoming.post-created-in.value.deserializer=com.ariv.photoshare.events.PostCreatedEventDeserializer
mp.messaging.incoming.post-created-in.group.id=timeline-generator
mp.messaging.incoming.post-created-in.auto.offset.reset=earliest

mp.messaging.incoming.post-created-in.broadcast=true